<script setup lang="ts">
import { reactive, watch } from 'vue'

const props = withDefaults(defineProps<{ open:boolean; busy?:boolean; error?:string }>(),{busy:false,error:''})
const emit = defineEmits<{ close:[]; changePassword:[payload:{current_password:string;new_password:string;new_password_confirm:string}] }>()
const form=reactive({current:'',next:'',confirm:''});const errors=reactive({next:'',confirm:''})
watch(()=>props.open,(open)=>{if(open){form.current='';form.next='';form.confirm='';errors.next='';errors.confirm=''}})
function submit():void{const bytes=new TextEncoder().encode(form.next).length;errors.next=bytes<8||bytes>72||!/[A-Za-z]/.test(form.next)||!/\d/.test(form.next)?'新密码需为 8–72 字节，并包含字母和数字':'';errors.confirm=form.next===form.confirm?'':'两次输入的新密码不一致';if(!errors.next&&!errors.confirm)emit('changePassword',{current_password:form.current,new_password:form.next,new_password_confirm:form.confirm})}
</script>

<template><Transition name="dialog"><div v-if="open" class="dialog-layer" @click.self="emit('close')"><section class="password-dialog" role="dialog" aria-modal="true" aria-label="更新登录密码"><span>SECURITY CHECK</span><h2>更新登录密码</h2><p>保存后所有设备上的旧登录凭证都会立即失效。</p><form @submit.prevent="submit"><label><b>当前密码</b><input v-model="form.current" type="password" autocomplete="current-password"/></label><label><b>新密码</b><input v-model="form.next" type="password" autocomplete="new-password"/><small v-if="errors.next">{{ errors.next }}</small></label><label><b>确认新密码</b><input v-model="form.confirm" type="password" autocomplete="new-password"/><small v-if="errors.confirm">{{ errors.confirm }}</small></label><p v-if="error" class="api-error">{{ error }}</p><div class="dialog-actions"><button type="button" @click="emit('close')">暂不修改</button><el-button type="primary" native-type="submit" :loading="busy">更新并重新登录</el-button></div></form></section></div></Transition></template>

<style scoped>.dialog-layer{background:rgba(20,13,35,.5);display:grid;inset:0;padding:20px;place-items:center;position:fixed;z-index:220;backdrop-filter:blur(10px)}.password-dialog{background:radial-gradient(circle at 100% 0,#e8ddff,transparent 30%),white;border:1px solid #e3dcf0;border-radius:24px;box-shadow:0 30px 90px rgba(29,18,54,.3);padding:27px;width:min(430px,92vw)}.password-dialog>span{color:#7657df;font-family:var(--font-mono);font-size:9px;letter-spacing:.17em}.password-dialog h2{font-size:25px;margin:7px 0}.password-dialog>p{color:#897e95;font-size:12px;line-height:1.6}.password-dialog form{display:grid;gap:15px;margin-top:20px}.password-dialog label{display:grid;gap:6px}.password-dialog label b{color:#44384f;font-size:12px}.password-dialog input{border:1px solid #ded6eb;border-radius:12px;font:inherit;height:43px;padding:0 12px}.password-dialog small,.api-error{color:#c83d5a;font-size:10px}.dialog-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:8px}.dialog-actions>button{background:transparent;border:0;color:#7f748c;cursor:pointer}.dialog-enter-active,.dialog-leave-active{transition:.22s}.dialog-enter-from,.dialog-leave-to{opacity:0}.dialog-enter-from .password-dialog,.dialog-leave-to .password-dialog{transform:translateY(10px) scale(.96)}@media(prefers-reduced-motion:reduce){.dialog-enter-active,.dialog-leave-active{transition:none}}</style>
