<script setup lang="ts">
import { ChatDotRound, Check, ShoppingCart } from '@element-plus/icons-vue'

import type { AccountActivity } from '@/types'

defineProps<{ items: readonly AccountActivity[]; hasMore: boolean; loadingMore: boolean }>()
const emit = defineEmits<{ select: [activity: AccountActivity]; loadMore: [] }>()
const icons = { chat: ChatDotRound, advisor: ShoppingCart, feedback: Check }
const labels = { chat: '可信问答', advisor: 'AI 选购', feedback: '互动反馈' }
function formatTime(value:string):string{return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}
</script>

<template><section class="timeline-card"><header><div><span>RECENT JOURNEY</span><h2>最近旅程</h2></div><p>点击即可继续上次探索</p></header><div v-if="items.length" class="timeline"><button v-for="item in items" :key="item.id" type="button" :data-activity-id="item.id" @click="emit('select',item)"><i><component :is="icons[item.type]"/></i><div><span>{{ labels[item.type] }} · {{ formatTime(item.occurred_at) }}</span><strong>{{ item.title }}</strong><p>{{ item.summary }}</p></div><b>继续 →</b></button></div><div v-else class="timeline-empty"><b>还没有旅程记录</b><p>去问答或 AI 选购页开启第一次探索。</p></div><el-button v-if="hasMore" class="load-more" :loading="loadingMore" @click="emit('loadMore')">查看更多旅程</el-button></section></template>
<style scoped>.timeline-card{background:rgba(255,255,255,.82);border:1px solid #e5dff0;border-radius:24px;padding:23px}.timeline-card header{align-items:end;display:flex;justify-content:space-between;margin-bottom:10px}.timeline-card header span{color:#7556dc;font-family:var(--font-mono);font-size:9px;letter-spacing:.16em}.timeline-card h2{font-size:23px;margin:5px 0}.timeline-card header p{color:#978da3;font-size:11px}.timeline{display:grid}.timeline button{align-items:center;background:transparent;border:0;border-bottom:1px solid #eee9f5;cursor:pointer;display:grid;gap:13px;grid-template-columns:auto 1fr auto;padding:15px 4px;text-align:left;transition:.2s;width:100%}.timeline button:hover{background:#f7f3ff;padding-left:10px}.timeline button>i{background:linear-gradient(135deg,#7657df,#cf5ccf);border-radius:12px;color:white;display:grid;height:38px;place-items:center;width:38px}.timeline button span{color:#968ba4;font-size:9px}.timeline button strong{color:#332942;display:block;font-size:13px;margin:3px 0}.timeline button p{color:#81778d;font-size:11px;margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.timeline button>b{color:#7657d4;font-size:10px}.timeline-empty{padding:50px 10px;text-align:center}.timeline-empty p{color:#93899e;font-size:12px}.load-more{margin-top:16px;width:100%}@media(max-width:600px){.timeline button>b{display:none}.timeline-card header p{display:none}}@media(prefers-reduced-motion:reduce){.timeline button{transition:none}}</style>
